service: stepfunction-serverlessframework-travis
frameworkVersion: '2'

plugins:
  - serverless-step-functions
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: sa-east-1

functions:
  initialize:
    handler: initialize.handler_initialize
  paginated:
    handler: paginated.handler_paginated

stepFunctions:
  stateMachines:
    paginatedInfo:
      name: paginatedInfo
      events:
        - schedule: cron(0 12 * * ? *)
      definition:
        StartAt: Initialize
        States:
          Initialize:
            Type: Task
            Resource:
              Fn::GetAtt: [initialize,Arn]
            Next: Paginated
            ResultPath: "$"
            TimeoutSeconds: 10
          Paginated:
            Type: Task
            Resource:
              Fn::GetAtt: [paginated,Arn]
            Next: IsCompleted
            ResultPath: "$"
            TimeoutSeconds: 600
          IsCompleted:
            Type: Choice
            Choices:
            - Variable: "$.is_completed"
              BooleanEquals: true
              Next: End
            Default: Paginated
          End:
            Type: Pass
            End: true
